### ISSUE TITLE
Please update your API

### ISSUE THREAD

**Issue by nsde** [Fortnite-API/py-wrapper#13]
[Update/Edit - This is the wrong repository!]

**Comment by Luc1412** [comment]
What should be updated? The wrapper includes the latest features from fortnite-api.com

**Comment by nsde** [comment]
Oh, it has just been updated today or yesterday. Thanks!

**Comment by Luc1412** [comment]
Keep in mind that this repository is just related to the wrapper, not the api itself.

**Comment by nsde** [comment]
> Keep in mind that this repository is just related to the wrapper, not the api itself.

Oh, yeah, you're right. Sorry, I didn't think about this. Thanks for maintaining the wrapper!

**Comment by nsde** [comment]
Or, as we in German would say: da war ich bissl lost
