### ISSUE TITLE
How to draw POI location coordinates using opencv

### ISSUE THREAD

**Issue by dlprisco** [Fortnite-API/py-wrapper#16]
I want to make a program that download the poi imagen of the map and then use poi location coordinates in *x, y* format and use opencv to draw this points on the image, but i am unable to do it, this is what i have tried:

```
>>> import requests
>>> map = api.map.fetch()
>>> map_poi = map.poi_image
>>> map_poi
'https://fortnite-api.com/images/map_en.png'
>>> r = requests.get(map_poi, stream=True)
>>> r.raise_for_status()
>>> r.raw.decode_content = True
>>> img = Image.open(r.raw)
>>> red = [0,0,255]
>>> map.pois[0].location.x
43512
>>> map.pois[0].location.y
-19416
```
However when i try to set the **red** color to the `x, y` coordinate i get this error:

```
>>> x_img[map.pois[0].location.x, map.pois[0].location.y] = red
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 43512 is out of bounds for axis 0 with size 2048
```
I think a possible solution could be to divide this value by the lenght of the image (2048) or any other related value, what could be the best approach to draw POI location coordinates?

**Comment by alexraskin** [comment]
So I asked in the discord about the cords that the API returns. It sounds like these cords are for the ingame map, not the map the API returns.

**Comment by alexraskin** [comment]
Based on the labels from this [map](https://fortnite-api.com/images/map_en.png), I did the best I could getting the coordinates. 

```python
map_cords = {
    "SHADY STILTS": (943, 517),
    "SLAPPY SHORES": (1537, 957),
    "KENJUTSU CROSSING": (1467, 1771),
    "STEAMY SPRINGS": (1060, 1666),
    "KNOTTY NETS": (1744, 1499),
    "MEGA CITY": (1303, 1441),
    "FRENZY FIELDS": (868, 1447),
    "RELENTLESS RETREAT": (602, 1553),
    "SHATTERED SLABS": (519, 1202),
    "RUMBLE RUINS": (774, 1093),
    "CREEKY COMPOUND": (976, 903),
    "ECLIPSED ESTATE": (607, 794),
    "BREAKWATER BAY": (528, 487),
    "BRUTAL BASTION": (1338, 664),
    "SANGUINE SUITES": (1566, 518),
}
```

These coordinates are based on the image, not the ingame map.

**Comment by Luc1412** [comment]
The `x`, `y` and `z` are coordinates on the map. You require the world radius which is changing with any map.

Then you can use this formula:
```js
x = (apiY + worldRadius) / (worldRadius * 2) * mapWidth;
y = (1 - (apiX + worldRadius) / (worldRadius * 2)) * mapHight;
```
