### ISSUE TITLE
[Feature] Status and rank

### ISSUE THREAD

**Issue by pmatos** [Fortnite-API/py-wrapper#18]
It doesn't look like it's possible to see the status of someone through the API - i.e. if they are online, away, offline, etc. Also it's not possible to see current rank (Gold 1 30% for example). 

It would be great to have access to this information.

**Comment by Luc1412** [comment]
This isn't for feature request regarding Fortnite-API.com. This is just the wrapper.

Fortnite-API is currently not receiving new features and only will be maintained.

Also any 3rd party api won't be able to receive the online status of a player.
