### ISSUE TITLE
Add info regarding opt-in attributes

### ISSUE THREAD

**Issue by Luc1412** [Fortnite-API/py-wrapper#20]
The docs should include a warning/info for attributes that require opt in. The user should be also educated on how to opt-in.

This includes:
- `item_preview_hero_path`
- `display_asset_path`
- `definition_path`
- `path`
- `gameplay_tags`
- `shop_history`

**Comment by trevorflahardy** [comment]
As a side note, this would best be served as a custom sphinx directive for the sake of removing repetition.
