### ISSUE TITLE
http.py get_br_stats params 

### ISSUE THREAD

**Issue by osotelo** [Fortnite-API/py-wrapper#24]
Given i make a fetch_br_stats  request
AND pass the optional parameter time_window=TimeWindow.SEASON
When the request is executed
Then i see lifetime data in the response

Expected: I should see only the current season data.

my workaround: edit the http.py  get_br_stats method, line 332 'time_window key to 'timeWindow' 
That fixed my issue. I have not confirmed with get_br_stats_by_id.

<img width="985" alt="Screenshot 2024-09-08 at 2 38 46 PM" src="https://github.com/user-attachments/assets/03ebb6e1-4055-4b22-bbd3-4a590c6fddc9">

**Comment by Luc1412** [comment]
Thanks for reporting. Has been fixed with f766c6fc76f268af286361ea36eb49786f15afe4
