### ISSUE TITLE
fetch_cosmetic_br raises ServiceUnavailable

### ISSUE THREAD

**Issue by tsredanovic** [Fortnite-API/py-wrapper#36]
### Summary

fetch_cosmetic_br method raises fortnite_api.errors.ServiceUnavailable if provided with invalid cosmetic ID

### Reproduction Steps

Provide the `fetch_cosmetic_br` method with cosmetic ID which does not exist.

### Minimal Reproducible Code

```python
import fortnite_api

id = "some-invalid-id"
with fortnite_api.SyncClient() as client:
        client.fetch_cosmetic_br(id)
```

### Expected Results

Expected to raise `fortnite_api.NotFound`.

### Actual Results

Actually raised `fortnite_api.errors.ServiceUnavailable`.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my API key from display, if visible.

### Additional Context

Traceback:
```
# Error during code execution
PythonError: Traceback (most recent call last): File "/lib/python312.zip/_pyodide/_base.py", line 574, in eval_code_async await CodeRunner( File "/lib/python312.zip/_pyodide/_base.py", line 394, in run_async coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 5, in File "/lib/python3.12/site-packages/fortnite_api/client.py", line 1401, in fetch_cosmetic_br data = self.http.get_cosmetic_br( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.12/site-packages/fortnite_api/http.py", line 213, in get_cosmetic_br return self.request(r, params=params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.12/site-packages/fortnite_api/http.py", line 532, in request raise ServiceUnavailable('Service unavailable', response, data) fortnite_api.errors.ServiceUnavailable: Service unavailable
```

**Comment by Luc1412** [comment]
The actual issue you described isn't related to the wrapper. 
Fortnite-API returns a wrong HTTP code (`400` instead of `404`), so the wrapper won't return `NotFound`, since it's bound to the `404` status code. I reported that to Officer (Owner of Fortnite-API)

However returning `ServiceUnavilable` in this case makes no sense and is misleading. Instead a `HTTPException` should be raised in such case. We gonna fix that issue.
